# action.yml
name: 'galasactl Galasa command-line tool'
description: 'Use the galasactl tool from Galasa'
inputs:
  galasactl-args:  
    description: 'Arguments passed to the galasactl tool'
    required: true
  galasactl-version:
    description: 'The version of the galasactl tool you want to use. Defaults to main otherwise.'
    required: false
    default: main
runs:
  using: docker
  image: docker://icr.io/galasadev/galasa-cli-amd64:latest
  entrypoint: /bin/galasactl
  args:
    - ${{ inputs.galasactl-args }}
  