# action.yml
name: 'galasactl Galasa command-line tool'
description: 'Use the galasactl tool from Galasa'
inputs:
  galasactl_args:  
    description: 'Arguments passed to the galasactl tool'
    required: true
  galasactl_version:
    description: 'The version of the galasactl tool you want to use. Defaults to main otherwise.'
    required: false
    default: latest
runs:
  using: docker
  image: Dockerfile

  